
name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: banking-config-server  # set this to the name of your Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://cntrbanking.azurecr.io/
          username: ${{ secrets.AZURE_CREDENTIAL_USER }}
          password: ${{ secrets.AZURE_CREDENTIAL_PASSWORD }}
          
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}      
        
        
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cntrbanking.azurecr.io/${{ secrets.AZURE_CREDENTIAL_USER }}/banking-config-container:lastest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Development'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'cntrbanking.azurecr.io/${{ secrets.AZURE_CREDENTIAL_USER }}/banking-config-container:lastest'
          
