name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: banking-config-server  # set this to the name of your Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - run: mvn package -DskipTests
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jar-file
          path: target/banking-config-server-0.0.1-SNAPSHOT.jar
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - uses: actions/checkout@v3
      - name: Download JAR file
        uses: actions/download-artifact@v2
        with:
          name: jar-file
          path: target/
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - uses: azure/docker-login@v1
        with:
          login-server: cntrbanking.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -t cntrbanking.azurecr.io/banking-config-container:${{ github.sha }} .
          
      - uses: azure/docker-login@v1
        with:
          login-server: cntrbanking.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker push cntrbanking.azurecr.io/banking-config-container:${{ github.sha }}
          
      - uses: azure/webapps-deploy@v2
        with:
          app-name: banking-config-server
          images: cntrbanking.azurecr.io/banking-config-container:${{ github.sha }}
      - name: Azure logout
        run: |
          az logout
